const swaggerJsdoc = require("swagger-jsdoc");

const swaggerOptions = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "BITLINKS",
      version: "1.0.0",
      description: "API Documentation",
    },
    servers: [
      {
        url: "http://localhost:8000", 
      },
    ],
  },
  apis: [
    "./checkConnection/checkConnection.js", 
    "./PersonRoute/Person.js", 
    "./PersonRoute/SubConnection.js", 
    "./PersonRoute/PersonInfoId.js", 
    "./UserRoutes/UserNetworks.js", 
    "./UserRoutes/UserConnection.js", 
    "./UserRoutes/PersonStatus.js",
    "./UserRoutes/NetworkRanks.js",
    './UserRoutes/Summary.js',
    './UserRoutes/UserRanks.js',
    './TableData/DomainData.js',
    './TableData/RoleData.js',
    './TableData/SkillData.js',
    './TableData/LoginData.js',
    './UploadData/AlumniUpload.js',
    './UploadData/CompanyUpload.js',
    './UploadData/OutcomeUpload.js',
    './UploadData/PersonUpload.js',
    './UploadData/InternshipUpload.js',
    './UploadData/PlacementUpload.js',
    './UploadData/ConsultancyUpload.js',
    './UploadData/ExpertiseUpload.js',
    './UploadData/ExperienceUpload.js',
    './FieldData/PersonData.js',
    './FieldData/CompanyData.js',
    './FieldData/InternshipData.js',
    './FieldData/PlacementData.js',
    './FieldData/ConsultancyData.js',
    './FieldData/ExpertiseData.js',
    './FieldData/ExperienceData.js',
    './FieldData/AlumniData.js',
    './FieldData/OutcomeData.js',
    './FieldData/ExpertiseDomain.js',
    './Calls/AddHistory.js',
    './Calls/History.js',
    './Calls/HistoryStatus.js',
    './Calls/Schedule.js',
    './Calls/FetchScheduled.js',
    './Calls/AddMinutes.js',
    './Calls/Minutes.js',
    './Uploaded/Upload.js',
    './PostRest/UpdateMinutesPost.js',
    './PostRest/AddressData.js',
    './PostRest/AddressPost.js',
    './PostRest/CompanyData.js',
    './PostRest/CompanyPost.js',
    './PostRest/DomainPost.js',
    './PostRest/RolePost.js',
    './PostRest/SkillPost.js',
    './PostRest/LoginPost.js',
    './PostRest/UpdataStatus.js',
    './PostRest/UpdateStatusAddress.js',
    './PostRest/UpdateStatusCompany.js',
    './PostRest/UpdateStatusDomain.js',
    './PostRest/UpdateStatusRole.js',
    './PostRest/UpdateStatusSkill.js',
    './PostRest/UpdateStatusLogin.js',
    './PostRest/UpdateSaveMinutes.js',
    './PostRest/Interactions.js',
    
  ], 
};

const swaggerSpecial = swaggerJsdoc(swaggerOptions);

module.exports = swaggerSpecial;
